### ISSUE TITLE
Where do  you specify a query?

### ISSUE THREAD

**Issue by sckott** [idigbio-api-hackathon/blaschka#1]
On `Loading the data` page, when running the app I see 

> Query - You need to specify a query

But there is no where to specify a query. or did I miss it

**Comment by fmichonneau** [comment]
In the URL, something like:

http://127.0.0.1:5255/?rq={"genus":["holothuria"]}

the idea is that the app would be instantiated from the portal directly so there would be no need for the user to worry about it.

**Comment by sckott** [comment]
ah, okay, cool

i didn't know you could do that with shiny

**Comment by fmichonneau** [comment]
me neither until this morning :)
